#!/bin/sh

cp -av reposman.pl /myplace/workspace/perl/reposman
cp -av {lib,/myplace/workspace/perl/modules}/MyPlace/Reposman/Projects.pm
cp -av {lib,/myplace/workspace/perl/modules}/MyPlace/IniExt.pm
cp -av {lib,/myplace/workspace/perl/modules}/MyPlace/Script/Message.pm


